### ISSUE TITLE
In dark theme, change-server and opt-out-of-analytics buttons are black-on-black

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-android#1077]
### Steps to reproduce

1. Launch app on dark theme
2. Fail to find button to change server
3. Realise it's black on black

#### What did you expect?

Legible buttons

#### What happened instead?

https://www.google.co.uk/books/edition/The_Restaurant_at_the_End_of_the_Univers/r--6ujORIVgC?hl=en&gbpv=1&pg=PA121

### Application version and app store

0.1.2 (40001020) playstore

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment]
For `TextButton`s we're using the `LocalContentColor.current` value if it's specified. Weirdly enough, this is set up by default to `Color.Black` by the system, even if it's in dark mode and that's why it's displayed as a black text there. I think we should set up a default color per theme when we declare the theme itself.

**Comment by bmarty** [comment]
Also reported by Google pre-launch report. There is maybe other UI element to check.

<img width="1310" alt="image" src="https://github.com/vector-im/element-x-android/assets/3940906/bc518cb7-b453-421c-a734-6db9889410bf">
