### ISSUE TITLE
probably dark mode issue

### ISSUE THREAD

**Issue by kubo6472** [vector-im/element-x-android#120]
### Steps to reproduce

1. Download elementx dbg from actions
2. Install & open the app
3. See this

Can't send logs

#### What did you expect?

A working login flow

#### What happened instead?

![Screenshot_20230302-072435_ElementX_dbg](https://user-images.githubusercontent.com/26146502/222348738-a86d9377-f468-42bc-a74d-650ba6f02a1b.png)
![Screenshot_20230302-072443_ElementX_dbg](https://user-images.githubusercontent.com/26146502/222348752-7afc0164-5665-45b0-bf08-d1456d181586.png)

### Your phone model

Google Pixel 6a

### Operating system version

evolution_bluejay-userdebug 13 TQ1A.230205.002 1676718437 release-keys

### Application version and app store

version 0.1.0  io.element.android.x.dversion 0.1.0  io.element.android.x.debug versionCode 100100

### Homeserver

Conduit 0.5.0

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment]
Hi, thanks for reporting. This is a duplicate issue (see #115), a fix will be available once #100 is merged.

**Comment by kubo6472** [comment]
The invalid URL might be fixed, too?

**Comment by jmartinesp** [comment]
Sorry, I'm not sure what that issue is about, could you clarify it a bit?

Element X needs a server with sliding sync to work, and I believe only `matrix.org` is supported right now, so that might be what you're seeing. However, the Rust SDK version used in the app until very recently was a bit outdated and I remember someone mentioned it had issues with parsing some URLs, so that might be what you're seeing instead.

**Comment by kubo6472** [comment]
Okay, that explains it, thanks
