### ISSUE TITLE
[Design] Implement the bloom effect

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-x-android#1217]
Waiting for design confirmation.
@jmartinesp has already started working on it.

**Comment by jmartinesp** [comment]
I think I have a working implementation at the moment as a whole component, but I'd rather move to a `Modifier` solution. 

The implementation:
- Is based on BlurHash to generate the blur used based on some loaded Bitmap, so we have to find out how to integrate it with Coil. This avoids having to use `RenderEffect` for blurring, which only works on Android 12+, and it's quite efficient if we only calculate it once: since it's based on a single Bitmap it might not work great if we enable animated avatars.
- Given the currently picked blend modes for the 'blurred layers' ([HardLight](https://developer.android.com/reference/kotlin/androidx/compose/ui/graphics/BlendMode#Hardlight()), [Saturation](https://developer.android.com/reference/kotlin/androidx/compose/ui/graphics/BlendMode#Saturation())), we can only make it work down to API 29 (Android 10). In lower APIs the Bloom effect won't be visible. It's a shame, but it just isn't technically feasible to backport it any further.
