### ISSUE TITLE
Replies in the timeline are difficult to make out when using the device dark theme

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-x-android#134]
### Steps to reproduce

![image](https://user-images.githubusercontent.com/1342360/222960305-59dbc146-b4c4-4c94-b723-28073f5dfdeb.png)

The background of replies are very difficult to differentiate from the background of messages. The contrast between them is too low.

#### What did you expect?

To be able to differentiate at a glance whether text in a message is part of a reply or the message itself.

#### What happened instead?

The text from both a message and the message it is replying to (and the replied-to user's display name/Matrix ID) are all jumbled together.

### Your phone model

Google Pixel 4a 5G

### Operating system version

Android 13.0

### Application version and app store

commit `4125035c1a827a5b62fa10fd30a901cc22e61a0d`

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by kittykat** [comment]
@anoadragon453 The design has been updated since you filed the issue and currently looks like this:

![1000003414](https://github.com/vector-im/element-x-android/assets/51663/60e006be-6f7d-4379-9b9a-8ff62bb44a8a)

I'm going to close this issue for now, but if you feel that it could be improved further, please re-open!
