### ISSUE TITLE
[SS] Implements the SlidingSync strategy with multiple views

### ISSUE THREAD

**Issue by ganfra** [vector-im/element-x-android#143]
Makes sure to use the same strategy than on ElementX-iOS, with multiple sliding-sync views.

From this (internal) [doc](https://docs.google.com/document/d/1bDHb0RWrW0qyD0P5_CZCLtGs3T26iL2atqSJFhTG-3M):

- [ ] bg-pagination over all rooms in a big window which keeps expanding from [0,0] through to [0,6000], (starting with a small batch size (e.g 20) to rapidly load the first page and then switching to large batch side (e.g. 200) to quickly spider the remaining rooms) with limit=1 (or limit=0), with ephemeral data filtered out, used for fast-room-search, fast-roomlist-scrolling, and offline support (on LB mode, we could disable this and search serverside instead)
- [ ] maintain a smaller sliding window with per-room history limit=20 (or something) over the visible rooms, which overlaps the bg one, to precache history as you scroll around and display typing notifs in the roomlist, and to make subsequent room-views faster. (on LB mode, we could set limit=1 or even limit=0 if we don't want room previews). Means that we send some duplicate data between the two windows to clients. actually, SS is clever and deduplicates.
- [ ] when searching the room list, we should precache history for the rooms in the search results to make the subsequent room-view faster, by hitting /messages preemptively for search results (or a bulk /messages or bulk /what-history-would-sync-have-told-me endpoint in future). (not in LB mode)

**Comment by ara4n** [comment]
This is the ~Nov 2022 view of how to drive SS. It evolved a bit during the sprint for FOSDEM, off the top of my head:

 * the bg-pagination (called "AllRooms View" in EIX) runs with limit = 0, and grows in batches of 200.
 * the small window (called "VisibleRooms View" in EIX") starts with limit = 0, and then limit = 1, and then limit = 20. (The limit=0 isn't needed if the bg-pagination req handles it instead, and instead starts [0,20] and then [0,200], [0,400], etc) As the user scrolls around it switches to limit=1, and then back to limit=20 again once the scroll position settles, in order to precache the room history for the visible rooms in case the user wants to click on them.
 * we don't yet precache search result history (which is a bug) on EIX: https://github.com/vector-im/element-x-ios/issues/685

**Comment by pixlwave** [comment]
I've just checked the code,
- `AllRooms` works as described, except with batches of [100](https://github.com/vector-im/element-x-ios/blob/d3b304e92e0fa1e0419b93be037d2fe2539d7a2a/ElementX/Sources/Services/Client/ClientProxy.swift#L313).
- The `VisibleRooms` limit works as described, and the window starts as `[0, 20]`, but when the user scrolls it is [dynamically](https://github.com/vector-im/element-x-ios/blob/d3b304e92e0fa1e0419b93be037d2fe2539d7a2a/ElementX/Sources/Screens/HomeScreen/View/HomeScreen.swift#L215-L216) set to `[firstVisibleIndex - 5, lastVisibleIndex + 5]`.

**Comment by manuroe** [comment]
The logic will be managed in the SDK ([issue](https://github.com/matrix-org/matrix-rust-sdk/issues/1644)). We still need to use the new API in EAX when they will be ready.

**Comment by bmarty** [comment]
Now that Element X Android is using the RoomList API, I think we can close this issue.
