### ISSUE TITLE
You can send a space as a message

### ISSUE THREAD

**Issue by SandResidence** [vector-im/element-x-android#1463]
#### What would you like to do?
The title says it all.
In my opinion, this should not be possible and blocked as other instant messaging apps do.

#### Why would you like to do it?
Because.

### Have you considered any alternatives?

Not sending spaces? I don't know if it counts

### Additional context

Nope

### Are you willing to provide a PR?

No

**Comment by SandResidence** [comment]
Same with enters (new line characters)

**Comment by gdonval** [comment]
I am not sure special-casing this just "because" is a good idea. 

Blocking empty messages could make sense but even then that prevents the client from using them in interesting ways (e.g. as pings). E.g. Messenger sends an emoji on empty message. Element could use them to reprioritize notifications (i.e. giving people a nudge). Also special-casing is a burden and could break people's workflow just "because".

The only con of allowing sending such messages is that because it's a one-button press, it could happen that it's sent inadvertently pretty easily. But 1. we have edits 2. pressing any button prior to that will invalidate the check 3. a space does not convey any information that could be misconstrued by the other party as offensive 4. my experience has been receiving much more gibberish and unfinished messages in case of an involuntary send than nearly empty message or "thumb up emoji" on Messenger.

So I would say the behaviour is correct and as intended for a general-purpose messaging app.

**Comment by kittykat** [comment]
From a product point of view, we do not want to send messages that consist of spaces and/or new lines only. External contributions on this issue would be welcome.
