### ISSUE TITLE
Feature request: Include tracing log configuration in rageshake details

### ISSUE THREAD

**Issue by jplatte** [vector-im/element-x-android#1504]
It would be helpful for debugging if rageshake issue descriptions included the tracing configuration that determines what's (not) included in the log files.

**Comment by bmarty** [comment]
> The string has to be already available somewhere for you to be able to render it in settings, no?

Yes, but the setting can be changed by the user and if a rageshake occurs before the app is restarted, the tracing configuration will not match what the SDK has. It's maybe not a big deal, because it will be the case for the previous logs as well. SO if it's OK for you we could do that.

As a side note, I was discussing with @poljar about giving the opportunity to the SDK to log some data before sending the logs to a rageshake issue, in order to give some current status. It can be useful for instance to share information about the current crypto configuration like EW does:

<img width="371" alt="image" src="https://github.com/vector-im/element-x-android/assets/3940906/e2a07a92-bf71-450f-8abb-cd2fecd61ec4">

or the size of the DB or anything useful data and statistics. We had such [mechanism](https://github.com/vector-im/element-android/blob/develop/matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/Session.kt#L322) in the previous project.

**Comment by jplatte** [comment]
Maybe you should force-restart the app if the user changes the log settings? ^^

But even if not, I think changing those settings is uncommon enough that it's rarely going to be a problem. Also, we could look into making the log level dynamic (so app restarts are no longer required).
