### ISSUE TITLE
Allow users to access custom server settings before loading the homepage

### ISSUE THREAD

**Issue by arnewc** [vector-im/element-x-android#1553]
## Issue description:

I am using Element, a multi-platform client for logging into Matrix. When I use it in China, I cannot proceed to the next step of setting up a custom server, because the app tries to load a webpage that is blocked by the Chinese firewall. This prevents me from using the app with my preferred server.

I would like to request a feature that allows users to access the custom server settings before loading the homepage, so that users in this region can use the app more easily.

Thank you very much for your attention and work.

### Have you considered any alternatives?

A possible alternative is to modify the source code of the software and remove the code that accesses the relevant webpage, but this would cause many problems, such as the need to repackage and distribute the software, as well as issues of user trust.

### Additional context

 Please consider modifying the code for both Android and iOS platforms synchronously. Thank you very much.

### Are you willing to provide a PR?

Yes

**Comment by kittykat** [comment]
@arnewc What happens if you switch on airplane mode, navigate to the page where you can switch account provider, then disable airplane mode? Can you please share a screen recording?

**Comment by arnewc** [comment]
Okay, I tried it, this is the case when the flight mode is on, I took a picture, it is Chinese, the specific meaning is to say “no network” error, please check the network connection.
![c8b4ac9b16f8ebc600e49fd2d1420d6](https://github.com/vector-im/element-x-android/assets/8568181/055bfa80-632e-4f5e-8c10-274a5af5c22f)

**Comment by arnewc** [comment]
![bc70ea3370aaf0576730c137978d396](https://github.com/vector-im/element-x-android/assets/8568181/dffd1fe0-2e57-4453-ace4-f32086221709)
I seem to be unable to upload videos, if the network connection is normal, it will stay at the position shown in the picture for a long time.

**Comment by arnewc** [comment]
I can upload videos now, this is the video when the network connection is normal, it stays at this position for a long time.


https://github.com/vector-im/element-x-android/assets/8568181/8e48aae6-d3d9-4d6e-ac88-a3586b38267b

**Comment by arnewc** [comment]
When using VPN, the server settings page can appear normally, although it is a bit slow here because of the VPN speed.

https://github.com/vector-im/element-x-android/assets/8568181/4435c06c-335f-4c87-af87-1c479af84b1b

**Comment by kittykat** [comment]
It looks like you're using the legacy Element app ( [vector-im/element-android](https://github.com/vector-im/element-android) ), rather than Element X.

This repo is for the new app which is currently in development: you can see how the signin screen looks different [here](https://github.com/vector-im/element-x-android#screenshots). An Element X preview is currently available in the Google Playstore. Please note that the app is in pre-beta stage of development, but I personally use it every day and can confirm that it is already stable enough for what I do. You can check out Element X's feature list [here](https://github.com/vector-im/element-meta/issues/1915)

I am going to close this issue here because you are using a different app. Please note that we are no longer actively developing the legacy apps so issues filed against them are unlikely to be fixed. Your best option may be to try out Element X which does not have the issue that you are reporting
