### ISSUE TITLE
Android build to support own HomeServer

### ISSUE THREAD

**Issue by roughnecks** [vector-im/element-x-android#187]
Hello,

are there any instructions for this?

Thanks

**Comment by cvonderstein** [comment]
Hey, this is what I found to be working for me:

- Change `matrix.org` in [features/login/src/main/kotlin/io/element/android/features/login/util/LoginConstants.kt#L21](https://github.com/vector-im/element-x-android/blob/develop/features/login/src/main/kotlin/io/element/android/features/login/util/LoginConstants.kt#L21) to your Homeserver FQDN (e.g. `matrix.example.org`)

- Change `matrix.org` in [features/login/src/main/kotlin/io/element/android/features/login/root/LoginRootStateProvider.kt#L36](https://github.com/vector-im/element-x-android/blob/develop/features/login/src/main/kotlin/io/element/android/features/login/root/LoginRootStateProvider.kt#L36) to your Homeserver FQDN (e.g. `matrix.example.org`). You can ignore the `some-custom-server.com` in Line 27.

- Change all `matrix.org` occasions in [features/login/src/main/kotlin/io/element/android/features/login/changeserver/ChangeServerStateProvider.kt]( https://github.com/vector-im/element-x-android/blob/develop/features/login/src/main/kotlin/io/element/android/features/login/changeserver/ChangeServerStateProvider.kt) to your Homeserver FQDN (e.g. `matrix.example.org`)

- Change `https://slidingsync.lab.matrix.org` in [libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/RustMatrixClient.kt#L101](https://github.com/vector-im/element-x-android/blob/develop/libraries/matrix/impl/src/main/kotlin/io/element/android/libraries/matrix/impl/RustMatrixClient.kt#L101) to your sliding sync URL (you can find it in your `.well-known/matrix/client`)

There are lots of other occasions of the string `matrix.org` in the code, but they are mostly either in comments or in strings, which are the translation from my understanding. Due to this, you will probably see some `matrix.org` in the UI sometimes where your Homeserver should be mentioned, but I guess considering the current state of this app, this shouldn't be a problem.

Now, after I mentioned all code locations here, it would be nice if someone more familiar with the codebase could just change it to use the correct URLs for the selected Homeserver by default :)

**Comment by cvonderstein** [comment]
Quick Update: Its neither asking for nor showing verification requests, not sure if I missed something or if that is just not implemented yet.

**Comment by ganfra** [comment]
It's not implemented yet, but will be soon.
I'm closing the ticket as the app is not ready to be used yet.

**Comment by dead10ck** [comment]
@ganfra I'm confused, it's work that needs doing to make the app usable. Why did you close it? The fact that the app is pre-release doesn't really have anything to do with the fact that this issue needs tracking, does it?
