### ISSUE TITLE
Permission management

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-x-android#20]
Probably use https://google.github.io/accompanist/permissions/
Interesting reading: https://www.composables.co/blog/permissions

**Comment by manuroe** [comment]
We need it for March

**Comment by jmartinesp** [comment]
Since we don't have any permissions at the moment in the app and we agree on use Accompanist Permissions (in fact, it's already in the gradle setup), what should be the outcome of this task? Maybe a PR of runtime permissions for notifications in Android 13+?

**Comment by jmartinesp** [comment]
If we're just exploring the different approaches for permission management, I vote for using Accompanist directly wherever we need it. I don't really think we'll need a different module for this, as the library mostly covers all our use cases.

However, there's one special case: what happens when you have runtime permissions for a permission that isn't available in your `minSdkVersion`? Accompanist returns a `MutablePermissionState`, which is an internal implementation of the public interface `PermissionState`, but there's no 'no-op state' included, so we need to either:
 
 1. Create our own 'NotAvailablePermission` that always returns permission granted based on `PermissionState`.
 2. Wrap the original `val permissionState = if (Build.Version...)` with something else or change the check so we don't really need a `PermissionState` object.

I prefer the 1st option, as it allows us to use all the `PermissionState`s  in the same way with no exceptions.

**Comment by bmarty** [comment]
I am not sure to get your point about the special case, but I agree to use Accompanist.

I was wondering if we could integrate the debug screen for permission that we have on EA, but actually it is not that useful so it can be done later, if necessary:

<img width="332" alt="image" src="https://user-images.githubusercontent.com/3940906/222682596-75d70a10-1a7b-4299-b788-0c781c77fc87.png">

**Comment by jmartinesp** [comment]
Closed the issue as we agreed on using Accompanist without an external module for permissions. How to handle the corner case about permissions only available in certain APIs can be resolved later.
