### ISSUE TITLE
Why not support more platform?

### ISSUE THREAD

**Issue by Modificator** [vector-im/element-x-android#25]
rust and compose ([compose-jb](https://github.com/JetBrains/compose-jb)) both support multiplatform

why not try to add windows/mac/linux desktop support

**Comment by Lonami** [comment]
I can't speak for the maintainers of the project, but based on the README, this is currently in the "Proof of Concept" stage, so I would imagine, features they don't have a need for are simply not a priority (or perhaps the goal was never to push beyond PoC stage). Support for other platforms don't seem to be in their current plan.

However, because it's open source, you're more than welcome to fork the project and modify it to suit your needs.

**Comment by JokerGermany** [comment]
would be a dream not to relate on electron...

**Comment by ashughes1** [comment]
Closing as there are no official plans currently to support this. The issue can be reopened, or a new one filed, if this is something we decided to support in the future.
