### ISSUE TITLE
Design decisions - Why are UniFFI generated types wrapped in hand rolled types?

### ISSUE THREAD

**Issue by theIDinside** [vector-im/element-x-android#284]
I have a few questions regarding the use of the `rust-sdk`; and I keep seeing that so much of the `UniFFI` generated types are wrapped in hand rolled Kotlin types, which makes me wonder - why? Doesn't this defeat the purpose? 

 - 1: it means you now have to handroll everything in the rust-sdk which defeats the re-use argument, as you now have to handwrite everything anyhow; yes, without the implementation details of the Java Native Interface (JNI), but you've still added yet another layer on top of what UniFFI does so well.
 - 2:  It also defeats other benefits of UniFFI which is rapid adoption; since you're now wrapping the generated types in interfaces and implementing classes as well (!).

Is there something I'm missing? Because I'm seeing it _everywhere_ - from `MatrixClient` to `RustMatrixClient` to `Room` to `RustRoom` to `MatrixUser` (called `UserProfile` in Rust, and also called `UserProfile` in the generated FFI type) and even down to the record types; essentially tripling the complexity - because, on top of having the UniFFI created types, you now have an `interface` and an implementation `class` also.

**Comment by jmartinesp** [comment]
There are several reasons for this, although I agree some duplications could be avoided:

1. Anything that's not a pure record type and comes from Rust [will be a memory leak](https://mozilla.github.io/uniffi-rs/kotlin/lifetimes.html) unless you call its `close()` or `destroy()` methods, so most of the time we map those to our own objects in a `.use { ... }` block that automatically releases them.
2. When we wrap them in another class, we can also improve input/output and error handling.
3. UniFFI does produce interfaces for each class that's not a pure record type, but if you use these classes as parameters in functions or callbacks, the generated Kotlin code will use the class instead of the interface, so you need to pass the originally retrieved object instead of an abstraction of it. When we either wrap these objects, we can just mock/disable these function calls by adding an alternative or no-op implementation:

```kotlin
// Example of what the FFI generated code looks like, this is not real code
interface RoomInterface { ... }

class Room : RoomInterface { ... }

interface Client {
  // Not the interface, needs a real Rust object retrieved from Rust, that can become a memory leak
  fun joinRoom(room: Room) { ... }
}
```

If points 1 and 3 could be fixed then we could probably just use these objects right away, but I don't think they'll be fixed any time soon.

**Comment by theIDinside** [comment]
Right, I understand that as well, it just seemed like some of them do not have to be wrapped, like `SlidingSyncRoom` which is an `Arc<>` that will be pointing to an object that is persistent, once it's created. We can safely hold on to it instead of having Rust pass us a newly cloned `Arc` every time we want to use it - and destroy it at shutdown by some manager class object.

That answers my question, but I've thought of another one;

I'm starting to think, that maybe it would be better to write most of the client code directly in Rust? i.e. setting up listeners, processing of the data & client state (like applying diffs to the timeline, etc), all that, and then just have the Kotlin side be *thin* client that merely gets processed/finalized-for-display output from the Rust side? Wouldn't that solve all issues wrt life times and such since the only data passing the FFI-barrier would be "pure" data - or is this just not possible on current state of FFI on the JVM platform? Meaning, the Kotlin side would just represent UI, not actual client state? Or would this not be feasible (maybe it's even outside the scope of this project)?

**Comment by jmartinesp** [comment]
> I'm starting to think, that maybe it would be better to write most of the client code directly in Rust?

I think that's where we're heading to, but keep in mind both the Rust SDK and Element X are in quite early stages. In example, sliding sync is mostly managed right now in the platforms (Android/iOS) side but the Rust SDK team is internally working on handling all the hard bits inside the SDK, simplifying its usages as much as possible.

**Comment by jmartinesp** [comment]
Closing this issue as both questions have been answered and we're little by little moving most logic code to the Rust SDK. There has been some movement in UniFFi about memory handling and using interfaces, let's hope the discussion materializes and lets us improve our usage of the FFI bindings 🤞 .
