### ISSUE TITLE
[UI/UX] Improvements to room creation 

### ISSUE THREAD

**Issue by Aquathing** [vector-im/element-x-android#327]
#### What would you like to do?
1) Have a floating button, when searching for users, called "Next", which changes position according to the user's keyboard location which brings the user to the room creation page.
2) Don't require the invitee's username to start with '@' to start showing results.
3) While typing the username, also show the missing portion, so if the user is typing 'aquathing' the app should suggest to complete it with 'aquathing:matrix.org' or 'aquathing:server.org'. This should not be made in the form of a button, but rather as grey placeholder text just after the user input.
4) The list of selected people should show their full username.
#### Why would you like to do it?
1) It is disorienting not to see a next button because the user might forget they are in the search page.
2) One might forget to add the '@', or might be unfamiliar with matrix and get stuck.
3) Similarly, a new user might wonder why they can't find their peer. This should help them understand that a part of the username is missing.
4) The current UI cuts the username after just three characters, making it impossible to distinguish users without a profile pictures.

### Are you willing to provide a PR?

No

**Comment by kittykat** [comment]
Thank you for your feedback! There have been a lot of changes to room creation since this issue was filed and I think most of the points have been addressed in some way at this point. I'm going to close this issue for now, please open new issues if you feel that there are further improvements to be made, but it's worth bearing in mind that there is another design iteration due for this flow :+1:
