### ISSUE TITLE
Set up Element PR

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-x-android#33]
We need a link and a QR code on every PR so that people can test the change easily. Check iOS PRs like this [one](https://github.com/vector-im/element-x-ios/pull/306).
To save CI time, we should enable those builds only if the PR is labelled `Trigger-PR-Build`.

**Comment by bmarty** [comment]
OK so I tried to avoid using yet another external service provider such as [diawi](https://www.diawi.com) because:
- APKs uploaded to diawi live only 3 days (with the free plan), and GitHub artifacts live 90 days.
- we should be able to handle that manually, but this is not possible to get the artifact id (or it's URL) during the job running (see https://github.com/actions/upload-artifact/issues/50). Also artifact are not publicly available but this can be mitigated by using a service like https://nightly.link (and yet another external tool we would depend on) 
- If we could get the artifact URL, it could be converted to a nightly.link url, then to a QR code image, such as:

> https://github.com/vector-im/element-x-android/suites/11042565154/artifacts/560992830

not publicly available, becomes

> https://nightly.link/vector-im/element-x-android/suites/11042565154/artifacts/560992830

publicly available, then becomes

> https://chart.apis.google.com/chart?cht=qr&chs=300x300&chl=https://nightly.link/vector-im/element-x-android/suites/11042565154/artifacts/560992830

rendered as
<img src="https://chart.apis.google.com/chart?cht=qr&chs=300x300&chl=https://nightly.link/vector-im/element-x-android/suites/11042565154/artifacts/560992830"/>
in a GitHub comment.

But actually the artifact is a Zip file, and not an Apk, so the user will have to download the Zip file, unzip it, and open the Apk it contains to get the app. Extra manual steps, we want to limit that.

So I am resolved out of spite to configure diawi with a felling of not having the best solution, but it will be better than nothing.

**Comment by bmarty** [comment]
Done in #92
