### ISSUE TITLE
Integrate the notification permission screen design

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-x-android#897]
Currently we have a dialog, but we may keep it in case the notification permission is revoked later by the user?

The permission full screen  rational can be integrated, now that we have a correct ftue flow. Probably between the welcome screen and the analytics optin screen.

Design (to be confirmed): https://www.figma.com/file/o9p34zmiuEpZRyvZXJZAYL/FTUE?node-id=611%3A66472&mode=dev

<img width="357" alt="image" src="https://github.com/vector-im/element-x-android/assets/3940906/54358218-10a6-49eb-8232-0d7d100c4854">

**Comment by giomfo** [comment]
@bmarty we will not implement this second design. You should go for the suggested permission full screen rational

**Comment by jmartinesp** [comment]
The end goal of this issue is to replace the current dialog in the room list view asking for notification permissions with this new screen, right? So I have this question:

Should this screen only be displayed once to the user, when they log in and haven't granted or revoked permissions, as part of the FTUE (welcome screen, migration, analytics opt in, etc.), or should it appear on every app start as it does right now? Some users have complained this latter behavior is too aggressive if they've decided not to use the app with notifications, and I tend to agree.

I'm not sure who I should ask here: @VolkerJunginger , @giomfo ?

**Comment by giomfo** [comment]
> The end goal of this issue is to replace the current dialog in the room list view asking for notification permissions with this new screen, right? 

Yes

I would say to display this screen only once for the moment.
We may consider to introduce some other alerts later, like [this one](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=6082-151511&mode=design&t=wpuoLobgyqxJVS0O-4) designed to alert the user when the notifications are turned off in the device settings whereas they have been enabled in the app. This second alert is out of the topic here for the moment
