### ISSUE TITLE
Push notification doesn't lead to room but timeline

### ISSUE THREAD

**Issue by kongo09** [vector-im/element-x-android#972]
### Steps to reproduce

1. Click on a push notification

#### What did you expect?
End up in the timeline at the unread message

#### What happened instead?
End up in the room list

https://github.com/vector-im/element-x-android/assets/640121/ced6f15c-892c-4611-9475-0eadcd2c1f2a

### Your phone model

Pixel 5

### Operating system version

Android 13

### Application version and app store

Element X nightly 0.1.2-nightly (40001020)

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by kongo09** [comment]
This breaks the main user flow and feels like a blocker

**Comment by bmarty** [comment]
Thanks for reporting. This notification is a temporary notification that we display when the application cannot get the message content. It will be removed in the future. But I agree, that the app could be able to open the correct room. However, we do not do it because sometimes it can lead to an error screen. See the comment here:

https://github.com/vector-im/element-x-android/blob/develop/libraries/push/impl/src/main/kotlin/io/element/android/libraries/push/impl/notifications/factories/NotificationFactory.kt#L236

> Ideally we'd use `createOpenRoomPendingIntent` here, but the broken notification might apply to an invite and the user won't have access to the room yet, resulting in an error screen.

Also, since the user has no clue about which room will be opened, it's maybe better to open the room list, rather than a "random" room.

**Comment by kongo09** [comment]
This is 90% of the time the only type of notification I get. As a user, I find it useless and broken. If we don't know which room it belongs to, why are we even displaying it?

**Comment by kongo09** [comment]
Oh, and if it points to an invite, why are we not opening that corresponding room and instead of an error er sie a nice welcome screen with a join button?

**Comment by kongo09** [comment]
I'm not experiencing it anymore - will close.
